---
- hosts: all
  gather_facts: false
  connection: ansible.netcommon.netconf
  tasks:
  - name: render templates
    ansible.builtin.template:
      src: device_templates/main.j2
      dest: configs/{{inventory_hostname}}.txt
    delegate_to: localhost
  - name: push configs to device
    junipernetworks.junos.junos_config:
      src: configs/{{inventory_hostname}}.txt
      comment: automatic intent push
      update: replace